### PR TITLE
Rework the Docker inheritance and CI pipeline

### PR DESCRIPTION
**Pull request by karalekas**
Goals
------
- [x] Allow quilc to change quicklisp dependency version without an rpcq release
- [x] Start explicitly specifying the dependent image versions instead of using `latest`
- [x] Allow dependent image labels to be overridden during `docker build`
- [x] Have the quilc image depend on the latest qvm image (needed for unit tests)
- [x] Run the CI tests from within freshly-built quilc Docker images, rather than using the "build within a Docker image" out-of-the-box feature of GitLab CI (because you can only specify one image to build FROM, as opposed to the flexibility of multi-stage builds if you use your own Dockerfile)
- [x] Update the README to explain how to upgrade the Dockerfile

### CODE REVIEW

**Comment by ecpeterson** [comment]
Perhaps a premature approval, but so far things look fine

**Comment by karalekas** [comment]
For this to truly address all the problems that were raised, I'm going to need to spend some more time on this. Will mark as non-draft when it's ready 2 go.

**Comment by karalekas** [comment]
The next commit is where it starts 2 get tricky.

**Comment by karalekas** [comment]
This should be good to go now.

**Pull request merged**
