### PR TITLE
Bump version to 1.18.0

### PR DESCRIPTION
**Pull request by appleby**
## Additions and Improvements

- Synthesis of encoding circuits for stabilizer codes (@jmbr, #600)

  Added a new package `CL-QUIL.QUILEC` with support for stabilizer
  codes. See the README for more info.

  https://github.com/rigetti/quilc/blob/master/src/quilec/README.org

- COMPILER-HOOK *does not* mutate and *does* compress qubits (@notmgsk, #609)

  COMPILER-HOOK now takes an optional `:DESTRUCTIVE` keyword arg. If
  `NIL` (default), the input `PARSED-PROGRAM` is not mutated.

  Also, logical qubits in the input Quil program will be compressed
  when possible, so that compiling a program like "H 9" no longer
  fails when compiling for an ISA that has qubits numbered 0-8, e.g.
  Qubit compression is disabled when the requested rewiring mode is
  `:NAIVE` or when the program contains `PRAGMA PRESERVE_BLOCK`
  pragmas.

- Add SWANK server (@notmgsk, #615)

  A SWANK server can be enabled for debugging purposes via the
  `--swank-port` command line flag. The SWANK server is disabled for
  release builds.

- Better errors and coercing for param values (@rigettizach, #608)
- Don't print circuit definitions in batch mode (@notmgsk, #601)

## Bugfixes

- Allow freely parameterized RX gates (@notmgsk, #611)
- Remove extra sqrt in fidelity calculation (@notmgsk, #613)
- Use MAGICL:HERMITIAN-EIG rather than MAGICL:EIG in PARAMETRIC-PAULI-COMPILER (@notmgsk, #607)

## Misc

- If quilc is latest version, don't print the SDK version check log message (@notmgsk, #602)
- Install quilc to system in Docker builds (@notmgsk, #614)

### CODE REVIEW

**Comment by notmgsk** [comment]
Nice detail <3

**Comment by notmgsk** [comment]
@appleby Do we need to bump the RPCQ version in `Dockerfile`? I think we may.

**Comment by appleby** [comment]
> @appleby Do we need to bump the RPCQ version in `Dockerfile`? I think we may.

I think you're right. Good catch.

**Comment by appleby** [comment]
I'm just going to wait until the rpcq pipeline finishes so that the new rpcq Docker image is available

**Comment by appleby** [comment]
Bumped the qvm version while we're at it.

**Pull request merged**
