### PR TITLE
Configure host with --host

### PR DESCRIPTION
**Pull request by notmgsk**
e.g. using --host 127.0.0.1 restricts incoming connections to those
from localhost

### CODE REVIEW

**Comment by notmgsk** [comment]
@stylewarning those changes are less nice here, since there is some confusing between defaults for HTTP vs RPCQ.

When we get rid of HTTP, we can make those changes. Speaking of which, can we get rid of HTTP yet? @ecpeterson

**Comment by ecpeterson** [comment]
It's been more than a month: we can get rid of quilc's HTTP.

**Comment by stylewarning** [comment]
FWIW, someone on Twitter said they want the HTTP API. hth

**Comment by ecpeterson** [comment]
What I'm hearing is a request for `rpcq.js`.

**Comment by notmgsk** [comment]
@stevenheidel ^

**Comment by stylewarning** [comment]
@notmgsk You haven't convinced me that you can't use `:initial-value` despite the existence of the HTTP server. How is doing
```
:initial-value "*"
```
different from no `:initial-value` and having 
```
(unless host
  (setf host "*"))
```
? Same for port, etc.

**Comment by notmgsk** [comment]
@stylewarning both of those things are different in HTTP vs RPCQ, so how do you have a default?

**Comment by stylewarning** [comment]
The docs say:
```
    (("host") :type string :optional t :documentation "host on which to run the RPCQ server")
    (("port" #\p) :type integer :optional t :documentation "port to run the RPCQ server on")
```

I thought it's RPCQ only.

**Comment by notmgsk** [comment]
when you're right you're right

**Pull request merged**
